#!/usr/bin/env bash

set -eu
set -o pipefail

export SYNORDER_PATH=${SYNORDER_PATH:-$(dirname $0)}
export TMPDIR=${TMPDIR:-.}

modeldir=$SYNORDER_PATH/src/models/forest
traineddir=$SYNORDER_PATH/control/models

function usage {
    cat <<EOF
Usage: $0 OUTDIR

Runs pre-trained model on OUTDIR (created with preprocess_vcf)

Pretrained models found in: $traineddir
As necessary, uses TMPDIR='$TMPDIR'

Ranked results printed to stdout.
EOF
    exit 1
}

if [[ $# -ne 1 ]]; then
    usage
fi

echo "Command: $0 $@" >&2

outdir=$(readlink -e $1)

if [[ ! -e $modeldir/test ]]; then
    echo "Could not find test script: $modeldir/test" >&2
    exit 1
fi

ext=.std.mat
for mat in $outdir/*$ext; do
    if [[ ! -e $mat ]]; then
	echo "Error: expected $ext file in OUTDIR." >&2
	echo "Was preprocess_vcf successful?" >&2
	continue
    fi

    base=$(basename $mat $ext)
    synfile="$base.rare"
    if [[ ! -e $synfile ]]; then
	echo "Error: expected $synfile file in OUTDIR." >&2
	echo "Was preprocess_vcf successful?" >&2
	continue
    fi
    for modelfile in $traineddir/*.model; do
	pushd $modeldir > /dev/null
	if [[ ! -e $modelfile ]]; then
	    echo "Error: could not find saved model: $modelfile" >&2
	    echo "Was preprocess_vcf successful?" >&2
	    exit 1
	fi

	# Run saved model on MAT file and created score file
	scorefile=$(basename $modelfile .model).scored
	if [[ ! -e $outdir/$scorefile ]]; then
	    ./test $modelfile $mat | cut -f 1 > $outdir/.$scorefile \
		&& mv $outdir/.$scorefile $outdir/$scorefile
	fi
	popd > /dev/null
    done
done



echo "$0: SUCCESS" >&2