#!/usr/bin/env bash

set -eu
set -o pipefail

source $(dirname $0)/init.sh

modeldir=$SYMPRI_PATH/src/models/forest
traineddir=$SYMPRI_PATH/data/control/models
controlstats=$SYMPRI_CONTROL.stats

function usage {
    cat <<EOF
Usage: $0 OUTDIR

Runs pre-trained model on OUTDIR (created with preprocess_vcf)

Pretrained models found in: $traineddir
As necessary, uses TMPDIR='$TMPDIR'

Ranked results printed to stdout.
EOF
    exit 1
}

if [[ $# -ne 1 ]]; then
    usage
fi

init_message

outdir="$(cd -P "$1"; pwd)"

if [[ ! -e $modeldir/test ]]; then
    echo "Could not find test script: $modeldir/test" >&2
    exit 1
fi

ext=.std.mat
for mat in $outdir/*$ext; do
    if [[ ! -e $mat ]]; then
	echo "Error: expected $ext file in OUTDIR." >&2
	echo "Was preprocess_vcf successful?" >&2
	exit 1
    fi

    base=$(basename $mat $ext)
    synfile="$base.rare"
    matfile="$base.std.mat"
    if [[ ! -e $outdir/$synfile ]]; then
	echo "Error: expected $synfile file in OUTDIR." >&2
	echo "Was preprocess_vcf successful?" >&2
	exit 1
    fi
    if [[ ! -e $outdir/$matfile ]]; then
	echo "Error: expected $matfile file in OUTDIR." >&2
	echo "Was preprocess_vcf successful?" >&2
	exit 1
    fi
    for modelfile in $traineddir/*.model; do
	pushd $modeldir > /dev/null
	if [[ ! -e $modelfile ]]; then
	    echo "Error: could not find saved model: $modelfile" >&2
	    echo "Was preprocess_vcf successful?" >&2
	    exit 1
	fi

	# Run saved model on MAT file and created score file
	model=$(basename $modelfile .model)
	scorefile=$model.scored
	if [[ ! -e $outdir/$scorefile ]]; then
	    echo "Running model $model..." >&2
	    ./test $modelfile $mat | cut -f 1 > $outdir/.$scorefile \
		&& mv $outdir/.$scorefile $outdir/$scorefile
	    test -e $outdir/$scorefile
	fi
	popd > /dev/null
    done

    # Print scored examples to stdout
    echo "Printing scored variants to stdout..." >&2
    $SYMPRI_PATH/src/util/summarize_scores.py $controlstats $outdir/$matfile $outdir/$synfile $outdir/*.scored

    break  # Only process first MAT file
done



echo "$0: SUCCESS" >&2