#!/usr/bin/env bash

set -eu
set -o pipefail

source $(dirname $0)/init.sh

control=$SILVA_CONTROL.merged.arff
src=$SILVA_PATH/src

synonymous="$src/input/synonymous.py -O ${SILVA_DATA}/refGene.pkl*"
gp1k="$src/input/1000gp.py dummy ${SILVA_DATA}/1000gp.refGene.pkl*"

function usage {
    cat <<EOF
Usage: $0 VCF OUTDIR

Annotates rare, synonymous variants in VCF file,
creating files necessary to run this tool.
OUTDIR should be a directory specific to the VCF file.

Existing files in OUTDIR are NOT overwritten, so this
script can be stopped and resumed.

Creates OUTDIR if it does not exit.
Will use TMPDIR='$TMPDIR' as needed.
EOF
    exit 1
}


if [[ $# -ne 2 ]]; then
    usage
fi
vcf="$1"
outdir="$2"

if [[ ! -e "$vcf" ]]; then
    echo -e "Error: missing input file: $vcf\n" >&2
    usage
fi

base=$(basename "$vcf" .vcf)

function skip_if_exists {
    local f="$1"
    if [[ -e "$f" ]]; then
	echo "Found existing: $f..." >&2
    fi
    test ! -e "$f"
}

init_message
echo "SILVA_AF_MIN:    '$SILVA_AF_MIN'" >&2
echo -e "SILVA_AF_MAX:    '$SILVA_AF_MAX'\n" >&2

mkdir -pv $outdir
# Filter to just synonymous variants
# Adds gene and transcript information
out=$base.syn
skip_if_exists $outdir/$out \
    && echo "Filtering for synonymous exonic variants..." >&2 \
    && $synonymous filter $vcf | egrep -v "^Y\b" > $TMPDIR/$out \
    && echo "Removing variants on chromosome Y..." >&2 \
    && mv $TMPDIR/$out $outdir/$out
test -e $outdir/$out

# Annotate 1000 Genomes Project AF
out=$base.af
skip_if_exists $outdir/$out \
    && echo "Annotating with 1000 Genomes Project allele frequency..." >&2 \
    && cut -f 1,2,5 $outdir/$base.syn \
       | $gp1k \
       | paste - $outdir/$base.syn \
       > $TMPDIR/$out \
    && mv $TMPDIR/$out $outdir/$out
test -e $outdir/$out

out=$base.af-flt
skip_if_exists $outdir/$out \
    && echo "Filtering by allele frequency..." >&2 \
    && awk -F"\t" '{if ($1 == ".") {$1 = 0} if ($1 >= '"$SILVA_AF_MIN"' && $1 <= '"$SILVA_AF_MAX"') {print $0}}' $outdir/$base.af \
       | cut -f 2- \
       > $TMPDIR/$out \
    && mv $TMPDIR/$out $outdir/$out
test -e $outdir/$out

# Annotate with mrna sequence
out=$base.mrna
skip_if_exists $outdir/$out \
    && echo "Annotating with mRNA sequence..." >&2 \
    && $synonymous annotate $outdir/$base.af-flt > $TMPDIR/$out \
    && mv $TMPDIR/$out $outdir/$out
test -e $outdir/$out

# Annotate with features
out=$outdir/$base.raw.mat
skip_if_exists $out \
    && echo "Annotating features from MRNA file..." >&2 \
    && $src/convert/mrna2mat.sh $outdir/$base.mrna $outdir/$base.raw
test -e $out

# Reformat matrix for WEKA
out=$outdir/$base.raw.arff
skip_if_exists $out \
    && echo "Creating ARFF file (for WEKA)..." >&2 \
    && $src/convert/mat2arff.sh "$base" 0 $outdir/$base.raw{.mat,}
test -e $out

# Standardize according to training dataset
out=$base.std.arff
skip_if_exists $outdir/$out \
    && echo "Standardizing ARFF file according to control data..." >&2 \
    && java -Xmx1800m weka.filters.unsupervised.attribute.Standardize \
       -b -i $control -o /dev/null -r $outdir/$base.raw.arff -s $TMPDIR/$out \
    && mv $TMPDIR/$out $outdir/$out
test -e $outdir/$out

# Convert back into mat for analysis
out=$base.std.mat
skip_if_exists $outdir/$out \
    && echo "Creating MAT file to provide to model..." >&2 \
    && $src/convert/arff2mat.sh $outdir/$base.std.arff > $TMPDIR/$out \
    && mv $TMPDIR/$out $outdir/$out
test -e $outdir/$out

echo "$0: SUCCESS" >&2