#!/usr/bin/env python
from __future__ import with_statement, division

import sys
import cPickle

from numpy import array, concatenate

modelfile, trainfile = sys.argv[1:]

def read_data(file):
    with open(file) as ifp:
        # Read training dataset
        data = []
        solutions = []
        for line in ifp:
            line = line.strip()
            if not line or line.startswith('#'): continue
            values = [float(val) for val in line.split()]
            soln = int(values.pop(0))
            data.append(values)
            solutions.append(soln)
            
        print >>sys.stderr, "Loaded %s (%d variants)" % (file, len(data))
        return array(solutions, dtype=int), array(data, dtype=float)
            
            
train_solns, train_data = read_data(trainfile)

from milk.supervised import randomforest

learner = randomforest.rf_learner(rf=101)
model = learner.train(train_data, train_solns)

with open(modelfile, 'wb') as ofp:
    cPickle.dump(model, ofp, 2)
